services:
  frontend:
    container_name: frontend
    build: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    expose:
      - 3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  proxy:
    image: nginx:stable-alpine3.20
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build:/etc/nginx/build
    ports:
      - 100:100
    restart: unless-stopped